site_name: Bionic Framework
site_url: 'https://bionicframework.github.io/Documentation/'
repo_name: 'BionicFramework/Documentation'
repo_url: 'https://github.com/bionicframework/Documentation'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/bionicframework'
    - type: 'youtube'
      link: 'https://www.youtube.com/playlist?list=PLLxOHqHInCELJjnvN_rCKx5pa_53Utjr7'
  disqus: 'bionic-framework'
theme:
  name: material
  logo:
    icon: 'library_books'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite
